# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_trading_add_strategy.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autotrading_add_strategy_page(object):
    def setupUi(self, autotrading_add_strategy_page):
        autotrading_add_strategy_page.setObjectName("autotrading_add_strategy_page")
        autotrading_add_strategy_page.resize(1280, 720)
        autotrading_add_strategy_page.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(autotrading_add_strategy_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(autotrading_add_strategy_page)
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 691, 509))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.auto_trading_add_strategy_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.auto_trading_add_strategy_label.setObjectName("auto_trading_add_strategy_label")
        self.verticalLayout_3.addWidget(self.auto_trading_add_strategy_label)
        self.auto_trading_add_strategy_strategy_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents_5)
        self.auto_trading_add_strategy_strategy_list.setObjectName("auto_trading_add_strategy_strategy_list")
        self.verticalLayout_3.addWidget(self.auto_trading_add_strategy_strategy_list)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.auto_trading_add_strategy_risk_management_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents_5)
        self.auto_trading_add_strategy_risk_management_list.setObjectName("auto_trading_add_strategy_risk_management_list")
        self.verticalLayout_3.addWidget(self.auto_trading_add_strategy_risk_management_list)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.listWidget_3 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_5)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_3.addWidget(self.listWidget_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.auto_trading_add_strategy_descriptionl_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.auto_trading_add_strategy_descriptionl_label.setObjectName("auto_trading_add_strategy_descriptionl_label")
        self.verticalLayout_2.addWidget(self.auto_trading_add_strategy_descriptionl_label)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.textEdit_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_2.addWidget(self.textEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_4.addWidget(self.scrollArea_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.auto_trading_add_strategy_cancel_1_button = QtWidgets.QPushButton(self.page)
        self.auto_trading_add_strategy_cancel_1_button.setObjectName("auto_trading_add_strategy_cancel_1_button")
        self.horizontalLayout.addWidget(self.auto_trading_add_strategy_cancel_1_button)
        self.auto_trading_add_strategy_next_1_button = QtWidgets.QPushButton(self.page)
        self.auto_trading_add_strategy_next_1_button.setObjectName("auto_trading_add_strategy_next_1_button")
        self.horizontalLayout.addWidget(self.auto_trading_add_strategy_next_1_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 691, 509))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_6.addWidget(self.comboBox_3)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 667, 83))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 667, 84))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.addWidget(self.scrollArea_3)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 667, 83))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_8.addWidget(self.scrollArea_5)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_12.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(autotrading_add_strategy_page)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(autotrading_add_strategy_page)

    def retranslateUi(self, autotrading_add_strategy_page):
        _translate = QtCore.QCoreApplication.translate
        autotrading_add_strategy_page.setWindowTitle(_translate("autotrading_add_strategy_page", "Dialog"))
        self.auto_trading_add_strategy_label.setText(_translate("autotrading_add_strategy_page", "Strategy list"))
        self.label_9.setText(_translate("autotrading_add_strategy_page", "Risk management list"))
        self.label_12.setText(_translate("autotrading_add_strategy_page", "News reactor list"))
        self.auto_trading_add_strategy_descriptionl_label.setText(_translate("autotrading_add_strategy_page", "Strategy description"))
        self.label_10.setText(_translate("autotrading_add_strategy_page", "Risk management description"))
        self.label_13.setText(_translate("autotrading_add_strategy_page", "News reactor description"))
        self.auto_trading_add_strategy_cancel_1_button.setText(_translate("autotrading_add_strategy_page", "Cancel"))
        self.auto_trading_add_strategy_next_1_button.setText(_translate("autotrading_add_strategy_page", "Next step"))
        self.label_2.setText(_translate("autotrading_add_strategy_page", "Strategy input settings"))
        self.label_7.setText(_translate("autotrading_add_strategy_page", "Strategy name"))
        self.label.setText(_translate("autotrading_add_strategy_page", "Symbol"))
        self.label_3.setText(_translate("autotrading_add_strategy_page", "Timeframe"))
        self.label_4.setText(_translate("autotrading_add_strategy_page", "Position sizing settings"))
        self.label_11.setText(_translate("autotrading_add_strategy_page", "Selected risk management"))
        self.label_6.setText(_translate("autotrading_add_strategy_page", "Strategy settings"))
        self.label_5.setText(_translate("autotrading_add_strategy_page", "Selected trading strategy"))
        self.label_14.setText(_translate("autotrading_add_strategy_page", "Selected news reactor"))
        self.label_8.setText(_translate("autotrading_add_strategy_page", "News reactor setting"))
        self.pushButton_2.setText(_translate("autotrading_add_strategy_page", "Cancel"))
        self.pushButton_3.setText(_translate("autotrading_add_strategy_page", "Back"))
        self.pushButton.setText(_translate("autotrading_add_strategy_page", "Add strategy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autotrading_add_strategy_page = QtWidgets.QDialog()
    ui = Ui_autotrading_add_strategy_page()
    ui.setupUi(autotrading_add_strategy_page)
    autotrading_add_strategy_page.show()
    sys.exit(app.exec_())
