# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        Main.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 184, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 184, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tableWidget1 = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tableWidget1.setFont(font)
        self.tableWidget1.setLineWidth(2)
        self.tableWidget1.setRowCount(10)
        self.tableWidget1.setColumnCount(10)
        self.tableWidget1.setObjectName("tableWidget1")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tableWidget1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidget1_2 = QtWidgets.QTableWidget(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tableWidget1_2.setFont(font)
        self.tableWidget1_2.setLineWidth(2)
        self.tableWidget1_2.setRowCount(10)
        self.tableWidget1_2.setColumnCount(10)
        self.tableWidget1_2.setObjectName("tableWidget1_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1_2.setHorizontalHeaderItem(9, item)
        self.verticalLayout_2.addWidget(self.tableWidget1_2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrading = QtWidgets.QMenu(self.menubar)
        self.menuTrading.setObjectName("menuTrading")
        self.menuAutotrading = QtWidgets.QMenu(self.menubar)
        self.menuAutotrading.setObjectName("menuAutotrading")
        self.menuCharts = QtWidgets.QMenu(self.menubar)
        self.menuCharts.setObjectName("menuCharts")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")                
        Main.setMenuBar(self.menubar)

        self.actionLogin = QtWidgets.QAction(Main)
        self.actionLogin.setCheckable(False)
        self.actionLogin.setObjectName("actionLogin")
        self.actionAccInfo = QtWidgets.QAction(Main)
        self.actionAccInfo.setObjectName("actionAccInfo")
        self.actionPositions = QtWidgets.QAction(Main)
        self.actionPositions.setObjectName("actionPositions")
        self.actionOpenPosition = QtWidgets.QAction(Main)
        self.actionOpenPosition.setObjectName("actionOpenPosition")
        self.actionView_Closed_Positions = QtWidgets.QAction(Main)
        self.actionView_Closed_Positions.setObjectName("actionView_Closed_Positions")

        self.actionAutotrading_panel=QtWidgets.QAction(Main)
        self.actionAutotrading_panel.setObjectName("actionAutotrading_panel")
        self.actionAutotrading_start_all=QtWidgets.QAction(Main)
        self.actionAutotrading_start_all.setObjectName("actionAutotrading_start_all")
        self.actionAutotrading_stop_all=QtWidgets.QAction(Main)
        self.actionAutotrading_stop_all.setObjectName("actionAutotrading_stop_all")

        self.actionCharts_price_chart=QtWidgets.QAction(Main)
        self.actionCharts_price_chart.setObjectName("actionCharts_price_chart")

        self.actionHelp_instructions=QtWidgets.QAction(Main)
        self.actionHelp_instructions.setObjectName("actionHelp_instructions")

        self.menubar.addAction(self.menuTrading.menuAction())
        self.menubar.addAction(self.menuAutotrading.menuAction())
        self.menubar.addAction(self.menuCharts.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        
        self.menuTrading.addSeparator()
        self.menuTrading.addAction(self.actionLogin)
        self.menuTrading.addAction(self.actionAccInfo)
        self.menuTrading.addAction(self.actionPositions)
        self.menuTrading.addAction(self.actionView_Closed_Positions)
        self.menuTrading.addAction(self.actionOpenPosition)
        self.menuAutotrading.addAction(self.actionAutotrading_panel)
        self.menuAutotrading.addAction(self.actionAutotrading_start_all)
        self.menuAutotrading.addAction(self.actionAutotrading_stop_all)
        self.menuCharts.addAction(self.actionCharts_price_chart)
        self.menuHelp.addAction(self.actionHelp_instructions)
        
        

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.menuTrading.setTitle(_translate("Main", "Trading"))
        self.menuAutotrading.setTitle(_translate("Main", "Autotrading"))
        self.menuCharts.setTitle(_translate("Main", "Charts"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionLogin.setText(_translate("Main", "Login"))
        self.actionAccInfo.setText(_translate("Main", "Acc Info"))
        self.actionPositions.setText(_translate("Main", "View Open Positions"))
        self.actionOpenPosition.setText(_translate("Main", "Open Position"))
        self.actionView_Closed_Positions.setText(_translate("Main", "View Closed Positions"))
        self.actionAutotrading_panel.setText(_translate("Main", "Strategy panel"))
        self.actionAutotrading_start_all.setText(_translate("Main", "Start all strategies"))
        self.actionAutotrading_stop_all.setText(_translate("Main", "Stop all strategies"))
        self.actionCharts_price_chart.setText(_translate("Main", "Price chart"))
        self.actionHelp_instructions.setText(_translate("Main", "Instructions"))

        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Position Maker"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Currency"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("Main", "VisiblePl"))
        item = self.tableWidget1.horizontalHeaderItem(3)
        item.setText(_translate("Main", "GrossPl"))
        item = self.tableWidget1.horizontalHeaderItem(4)
        item.setText(_translate("Main", "Max Amount"))
        item = self.tableWidget1.horizontalHeaderItem(5)
        item.setText(_translate("Main", "Min Amount"))
        item = self.tableWidget1.horizontalHeaderItem(6)
        item.setText(_translate("Main", "Avg Amount"))
        item = self.tableWidget1.horizontalHeaderItem(7)
        item.setText(_translate("Main", "Number of trades"))
        item = self.tableWidget1.horizontalHeaderItem(8)
        item.setText(_translate("Main", "Number of successful trades"))
        item = self.tableWidget1.horizontalHeaderItem(9)
        item.setText(_translate("Main", "Number of unsuccessful trades"))        
        item = self.tableWidget1_2.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Position Maker"))
        item = self.tableWidget1_2.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Currency"))
        item = self.tableWidget1_2.horizontalHeaderItem(2)
        item.setText(_translate("Main", "VisiblePL"))
        item = self.tableWidget1_2.horizontalHeaderItem(3)
        item.setText(_translate("Main", "GrossPl"))
        item = self.tableWidget1_2.horizontalHeaderItem(4)
        item.setText(_translate("Main", "Max Amount"))
        item = self.tableWidget1_2.horizontalHeaderItem(5)
        item.setText(_translate("Main", "Min Amount"))
        item = self.tableWidget1_2.horizontalHeaderItem(6)
        item.setText(_translate("Main", "Avg Amount"))
        item = self.tableWidget1_2.horizontalHeaderItem(7)
        item.setText(_translate("Main", "Number of trades"))
        item = self.tableWidget1_2.horizontalHeaderItem(8)
        item.setText(_translate("Main", "Number of successful trades"))
        item = self.tableWidget1_2.horizontalHeaderItem(9)
        item.setText(_translate("Main", "Number of unsuccessful trades"))         
        self.label.setText(_translate("Main", "Leadership dashboards based on Positions"))
        self.label_3.setText(_translate("Main", "Open positions"))
        self.label_2.setText(_translate("Main", "Closed positions"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
