# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_orders.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Orders(object):
    def setupUi(self, Orders):
        Orders.setObjectName("Orders")
        Orders.resize(648, 280)
        self.gridLayout = QtWidgets.QGridLayout(Orders)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Orders)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 3, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Orders)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(31)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 4)
        self.pushButton = QtWidgets.QPushButton(Orders)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Orders)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Orders)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)

        self.retranslateUi(Orders)
        self.buttonBox.accepted.connect(Orders.accept)
        self.buttonBox.rejected.connect(Orders.reject)
        QtCore.QMetaObject.connectSlotsByName(Orders)

    def retranslateUi(self, Orders):
        _translate = QtCore.QCoreApplication.translate
        Orders.setWindowTitle(_translate("Orders", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Orders", "T"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Orders", "Rate precision"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Orders", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Orders", "Trade ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Orders", "Time"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Orders", "Account Name"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Orders", "Account ID"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Orders", "Time in force"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Orders", "Expire Date"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Orders", "Currency"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Orders", "Is Buy"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Orders", "Buy"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Orders", "Sell"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Orders", "Type"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Orders", "Status"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Orders", "Amount K"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("Orders", "Currency Point"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("Orders", "Stop Move"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("Orders", "Stop"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("Orders", "Stop Rate"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("Orders", "Limit"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("Orders", "Limit Rate"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("Orders", "Is Entry Order"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("Orders", "Oco Bulk ID"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("Orders", "Is Net Quantity"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("Orders", "Is Limited Order"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("Orders", "Is Stop Order"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("Orders", "Is ESL Order"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("Orders", "Stop Peg Base Type"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("Orders", "Limit Peg Base Type"))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("Orders", "Range"))
        self.pushButton.setText(_translate("Orders", "Close Order"))
        self.pushButton_2.setText(_translate("Orders", "Edit Order"))
        self.pushButton_3.setText(_translate("Orders", "Edit Limit/Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Orders = QtWidgets.QDialog()
    ui = Ui_Orders()
    ui.setupUi(Orders)
    Orders.show()
    sys.exit(app.exec_())
