# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_closed_positions.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClosedPositions(object):
    def setupUi(self, ClosedPositions):
        ClosedPositions.setObjectName("ClosedPositions")
        ClosedPositions.resize(1280, 600)
        self.gridLayout = QtWidgets.QGridLayout(ClosedPositions)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(ClosedPositions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(ClosedPositions)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(18)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 2)

        self.retranslateUi(ClosedPositions)
        self.buttonBox.accepted.connect(ClosedPositions.accept)
        self.buttonBox.rejected.connect(ClosedPositions.reject)
        QtCore.QMetaObject.connectSlotsByName(ClosedPositions)

    def retranslateUi(self, ClosedPositions):
        _translate = QtCore.QCoreApplication.translate
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ClosedPositions", "T"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ClosedPositions", "Rate Precision"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ClosedPositions", "Trade ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ClosedPositions", "Account Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ClosedPositions", "Roll"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ClosedPositions", "Com"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ClosedPositions", "Open"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ClosedPositions", "Value Date"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ClosedPositions", "Gross PL"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ClosedPositions", "Close"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ClosedPositions", "Visible PL"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ClosedPositions", "Currency"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ClosedPositions", "Is Buy"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("ClosedPositions", "Amount K"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("ClosedPositions", "Currency Point"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("ClosedPositions", "Open Time"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("ClosedPositions", "Close Time"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("ClosedPositions", "Position maker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClosedPositions = QtWidgets.QDialog()
    ui = Ui_ClosedPositions()
    ui.setupUi(ClosedPositions)
    ClosedPositions.show()
    sys.exit(app.exec_())
